runtime: nodejs10

handlers:
- url: /
  static_files: docs/.vuepress/dist/index.html
  upload: docs/.vuepress/dist/index.html
  
- url: /assets/
  static_dir: docs/.vuepress/dist/assets

- url: /(.+?)/?$
  static_files: docs/.vuepress/dist/\1/index.html
  upload: docs/.vuepress/dist/(.+?)/$index.html
  
- url: /
  static_dir: docs/.vuepress/dist